export const REGISTRO_EXISTOSO = 'REGISTRO_EXISTOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';